In [1]:
import numpy as np

In [2]:
x = np.arange(1, 17).reshape(4, 4)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [4]:
x_prime = np.roll(x, 1, axis=(0,1))
print(x_prime)

[[16 13 14 15]
 [ 4  1  2  3]
 [ 8  5  6  7]
 [12  9 10 11]]


In [5]:
x_prime = np.roll(x, -1, axis=(0,1))
print(x_prime)

[[ 6  7  8  5]
 [10 11 12  9]
 [14 15 16 13]
 [ 2  3  4  1]]


In [12]:
x_prime = np.roll(x, 1, axis=(-1,0))
print(x_prime)

[[16 13 14 15]
 [ 4  1  2  3]
 [ 8  5  6  7]
 [12  9 10 11]]
